package com.inf;

import com.inf.admin.IFieldsAdmin;

public interface IFields extends IFieldsAdmin {

	// SET OF FIELDS ON REPORT_BUFFER TABLES
	public final String REPORT_BUFFER_REPORT_ID = "REPORT_ID";
	public final String REPORT_BUFFER_REPORT_CODE = "REPORT_CODE";
	public final String REPORT_BUFFER_FULLNAME = "FULLNAME";
	public final String REPORT_BUFFER_SHORTNAME = "SHORTNAME";
	public final String REPORT_BUFFER_TYPE = "TYPE";
	public final String REPORT_BUFFER_DESCRIPTION = "DESCRIPTION";
	public final String REPORT_BUFFER_VERSION = "VERSION";
	public final String REPORT_BUFFER_START_DATE = "START_DATE";
	public final String REPORT_BUFFER_ACTIVE = "ACTIVE";
	public final String[] REPORT_BUFFER_ALL_FIELDS = {
			REPORT_BUFFER_REPORT_CODE, REPORT_BUFFER_FULLNAME,
			REPORT_BUFFER_SHORTNAME, REPORT_BUFFER_TYPE,
			REPORT_BUFFER_DESCRIPTION, REPORT_BUFFER_VERSION,
			REPORT_BUFFER_START_DATE, REPORT_BUFFER_ACTIVE };

	// SET OF FIELDS ON REPORT_NORM_BUFFER TABLES
	public final String REPORT_NORM_BUFFER_NORM_ID = "NORM_ID";
	public final String REPORT_NORM_BUFFER_REPORT_ID = "REPORT_ID";
	public final String REPORT_NORM_BUFFER_NORM_CODE = "NORM_CODE";
	public final String REPORT_NORM_BUFFER_NORM_NAME = "NORM_NAME";
	public final String REPORT_NORM_BUFFER_NORM_TYPE = "TYPE";
	public final String REPORT_NORM_BUFFER_NORM_TOTAL = "NORM_TOTAL";

	public final String REPORT_NORM_BUFFER_DESCRIPTION = "DESCRIPTION";
	public final String REPORT_NORM_BUFFER_VERSION = "VERSION";
	public final String REPORT_NORM_BUFFER_START_DATE = "START_DATE";
	public final String REPORT_NORM_BUFFER_ACTIVE = "ACTIVE";
	public final String[] REPORT_NORM_BUFFER_ALL_FIELDS = {
			REPORT_NORM_BUFFER_REPORT_ID, REPORT_NORM_BUFFER_NORM_CODE,
			REPORT_NORM_BUFFER_NORM_NAME, REPORT_NORM_BUFFER_NORM_TYPE,
			REPORT_NORM_BUFFER_NORM_TOTAL, REPORT_NORM_BUFFER_DESCRIPTION,
			REPORT_NORM_BUFFER_VERSION, REPORT_NORM_BUFFER_START_DATE,
			REPORT_NORM_BUFFER_ACTIVE };

	// SET OF FIELDS ON REPORTS_DATA_BUFFER TABLES
	public final String REPORTS_DATA_BUFFER_SRC_DATA_ID = "SRC_DATA_ID";
	public final String REPORTS_DATA_BUFFER_TICKET_ID = "TICKET_ID";
	public final String REPORTS_DATA_BUFFER_SRC_CONNECT_ID = "SRC_CONNECT_ID";
	public final String REPORTS_DATA_BUFFER_STATUS = "STATUS";
	public final String REPORTS_DATA_BUFFER_CREATE_BY = "CREATE_BY";
	public final String REPORTS_DATA_BUFFER_CREATION_DATE = "CREATION_DATE";
	public final String REPORTS_DATA_BUFFER_UPDATED_BY = "UPDATED_BY";
	public final String REPORTS_DATA_BUFFER_UPDATE_DATE = "UPDATE_DATE";
	public final String REPORTS_DATA_BUFFER_NORM_CODE = "NORM_CODE";
	public final String REPORTS_DATA_BUFFER_POSITION = "POSITION";
	public final String REPORTS_DATA_BUFFER_VALUE_NUMBER = "VALUE_NUMBER";
	public final String REPORTS_DATA_BUFFER_VALUE_TEXT = "VALUE_TEXT";
	public final String REPORTS_DATA_BUFFER_DESCRIPTION = "DESCRIPTION";
	public final String[] REPORTS_DATA_BUFFER_ALL_FIELDS = {
			REPORTS_DATA_BUFFER_SRC_DATA_ID, REPORTS_DATA_BUFFER_TICKET_ID,
			REPORTS_DATA_BUFFER_SRC_CONNECT_ID, REPORTS_DATA_BUFFER_STATUS,
			REPORTS_DATA_BUFFER_CREATE_BY, REPORTS_DATA_BUFFER_CREATION_DATE,
			REPORTS_DATA_BUFFER_UPDATED_BY, REPORTS_DATA_BUFFER_UPDATE_DATE,
			REPORTS_DATA_BUFFER_NORM_CODE, REPORTS_DATA_BUFFER_POSITION,
			REPORTS_DATA_BUFFER_VALUE_NUMBER, REPORTS_DATA_BUFFER_VALUE_TEXT,
			REPORTS_DATA_BUFFER_DESCRIPTION };

	// SET OF FIELDS ON SOURCE_CONNECT_TO_BUFFER TABLES
	public final String SOURCE_CONNECT_TO_BUFFER_SRC_CONNECT_ID = "SRC_CONNECT_ID";
	public final String SOURCE_CONNECT_TO_BUFFER_SRC_CODE = "SRC_CODE";
	public final String SOURCE_CONNECT_TO_BUFFER_FULLNAME = "FULLNAME";
	public final String SOURCE_CONNECT_TO_BUFFER_SHORTNAME = "SHORTNAME";
	public final String SOURCE_CONNECT_TO_BUFFER_TYPE = "TYPE";
	public final String SOURCE_CONNECT_TO_BUFFER_DESCRIPTION = "DESCRIPTION";
	public final String SOURCE_CONNECT_TO_BUFFER_URL = "URL";
	public final String SOURCE_CONNECT_TO_BUFFER_CONNECTION = "CONNECTION";
	public final String SOURCE_CONNECT_TO_BUFFER_ACTIVE = "ACTIVE";
	public final String SOURCE_CONNECT_TO_BUFFER_DES_CONNECT_ID = "DES_CONNECT_ID";
	public final String[] SOURCE_CONNECT_TO_BUFFER_ALL_FIELDS = {
			SOURCE_CONNECT_TO_BUFFER_SRC_CODE,
			SOURCE_CONNECT_TO_BUFFER_FULLNAME,
			SOURCE_CONNECT_TO_BUFFER_SHORTNAME, SOURCE_CONNECT_TO_BUFFER_TYPE,
			SOURCE_CONNECT_TO_BUFFER_DESCRIPTION, SOURCE_CONNECT_TO_BUFFER_URL,
			SOURCE_CONNECT_TO_BUFFER_CONNECTION,
			SOURCE_CONNECT_TO_BUFFER_ACTIVE,
			SOURCE_CONNECT_TO_BUFFER_DES_CONNECT_ID };

	// SET OF FIELDS ON SOURCE_ACCOUNT_BUFFER TABLES
	public final String SOURCE_ACCOUNT_BUFFER_ACCOUNT_ID = "ACCOUNT_ID";
	public final String SOURCE_ACCOUNT_BUFFER_ACCOUNT_PASS = "ACCOUNT_PASS";
	public final String SOURCE_ACCOUNT_BUFFER_FULLNAME = "FULLNAME";
	public final String SOURCE_ACCOUNT_BUFFER_SHORTNAME = "SHORTNAME";
	public final String SOURCE_ACCOUNT_BUFFER_SRC_CONNECT_ID = "SRC_CONNECT_ID";
	public final String SOURCE_ACCOUNT_BUFFER_DESCRIPTION = "DESCRIPTION";
	public final String SOURCE_ACCOUNT_BUFFER_QUOTA = "QUOTA";
	public final String SOURCE_ACCOUNT_BUFFER_ACTIVE = "ACTIVE";
	public final String[] SOURCE_ACCOUNT_BUFFER_ALL_FIELDS = {
			SOURCE_ACCOUNT_BUFFER_ACCOUNT_PASS, SOURCE_ACCOUNT_BUFFER_FULLNAME,
			SOURCE_ACCOUNT_BUFFER_SHORTNAME,
			SOURCE_ACCOUNT_BUFFER_SRC_CONNECT_ID,
			SOURCE_ACCOUNT_BUFFER_DESCRIPTION, SOURCE_ACCOUNT_BUFFER_QUOTA,
			SOURCE_ACCOUNT_BUFFER_ACTIVE };

	// SET OF FIELDS ON TICKET
	public final String TICKET_ID = "TICKET_ID";
	public final String TICKET_ID_ERR = "TICKET_ID_ERR";
	public final String TICKET_SRC_CONNECT_ID = "SRC_CONNECT_ID";
	public final String TICKET_STATUS = "STATUS";
	public final String TICKET_ACTIVE = "ACTIVE";
	public final String TICKET_EVN_ID = "EVN_ID";
	public final String TICKET_EVN_TIME = "EVN_TIME";
	public final String TICKET_BUFFER_ID = "BUFFER_ID";
	public final String TICKET_BUFFER_TIME = "BUFFER_TIME";
	public final String TICKET_EBS_ID = "EBS_ID";
	public final String TICKET_EBS_TIME = "EBS_TIME";
	public final String TICKET_START_TIME = "START_TIME";
	public final String TICKET_END_TIME = "END_TIME";
	public final String TICKET_TOTAL_RECORDS = "TOTAL_RECORDS";
	public final String TICKET_CODE = "CODE";
	public final String TICKET_TABLE_NAME = "TABLE_NAME";
	public final String TICKET_WHERES = "WHERE_DATA";
	public final String TICKET_DESCRIPTION = "ERROR_DESCRIPTION";
	public final String TICKET_DATA_FILE = "DATA_FILE";
	public final String TICKET_ERROR_CODE = "ERROR_CODE";
	public final String TICKET_PRIORITY_TIME = "PRIORITY_TIME";
	public final String[] TICKET_FIELDS_INSERT = { TICKET_ID, TICKET_ID_ERR,
			TICKET_SRC_CONNECT_ID, TICKET_STATUS, TICKET_ACTIVE, TICKET_EVN_ID,
			TICKET_EVN_TIME, TICKET_START_TIME, TICKET_END_TIME,
			TICKET_TOTAL_RECORDS, TICKET_CODE, TICKET_TABLE_NAME,
			TICKET_WHERES, TICKET_DESCRIPTION, TICKET_PRIORITY_TIME };

	public final String[] TICKET_ALL_FIELDS = { TICKET_ID, TICKET_ID_ERR,
			TICKET_SRC_CONNECT_ID, TICKET_STATUS, TICKET_ACTIVE, TICKET_EVN_ID,
			TICKET_EVN_TIME, TICKET_BUFFER_ID, TICKET_BUFFER_TIME,
			TICKET_EBS_ID, TICKET_EBS_TIME, TICKET_START_TIME, TICKET_END_TIME,
			TICKET_TOTAL_RECORDS, TICKET_CODE, TICKET_TABLE_NAME,
			TICKET_WHERES, TICKET_DESCRIPTION, TICKET_DATA_FILE,
			TICKET_ERROR_CODE, TICKET_PRIORITY_TIME };

	// SET OF FIELDS ON SOURCE_ACCOUNT_BUFFER TABLES
	public final String TABLES_ID = "ID";
	public final String TABLES_NAME = "NAME";
	public final String TABLES_SRC_CONNECT_ID = "SRC_CONNECT_ID";
	public final String TABLES_DESCRIPTION = "DESCRIPTION";
	public final String TABLES_KEY = "KEY";
	public final String TABLES_DES_CONNECT_ID = "DES_CONNECT_ID";
	public final String TABLES_DATA_FIELDS = "DATA_FIELDS";
	public final String[] TABLES_ALL_FIELDS = { TABLES_NAME, TABLES_KEY,
			TABLES_SRC_CONNECT_ID, TABLES_DESCRIPTION, TABLES_DES_CONNECT_ID,
			TABLES_DATA_FIELDS };

	// SET OF FIELDS ON ALERT_BUFFER TABLES
	public final String ALERT_BUFFER_ALERT_ID = "ALERT_ID";
	public final String ALERT_BUFFER_SRC_CONNECT_ID = "SRC_CONNECT_ID";
	public final String ALERT_BUFFER_TICKET_ID = "TICKET_ID";
	public final String ALERT_BUFFER_SRC_RECORD_ID = "SRC_RECORD_ID";
	public final String ALERT_BUFFER_STATUS = "STATUS";
	public final String ALERT_BUFFER_ERROR_CODE = "ERROR_CODE";
	public final String ALERT_BUFFER_ERROR_DESCRIPTION = "ERROR_DESCRIPTION";
	public final String ALERT_BUFFER_REQUEST_ID = "REQUEST_ID";
	public final String ALERT_BUFFER_DETECT_TIME = "DETECT_TIME";
	public final String ALERT_BUFFER_SENT_TIME = "SENT_TIME";
	public final String ALERT_BUFFER_TABLE_NAME = "TABLE_NAME";
	public final String ALERT_BUFFER_CONCURENT_ID = "CONCURENT_ID";
	public final String ALERT_BUFFER_DESCRIPTION = "DESCRIPTION";
	public final String ALERT_BUFFER_COMPLETE_STATUS="COMPLETE_STATUS";
	
	public final String[] ALERT_BUFFER_ALL_FIELDS = {
			ALERT_BUFFER_SRC_CONNECT_ID, ALERT_BUFFER_TICKET_ID,
			ALERT_BUFFER_SRC_RECORD_ID, ALERT_BUFFER_STATUS,
			ALERT_BUFFER_ERROR_CODE, ALERT_BUFFER_ERROR_DESCRIPTION,
			ALERT_BUFFER_REQUEST_ID, ALERT_BUFFER_DETECT_TIME,
			ALERT_BUFFER_SENT_TIME, ALERT_BUFFER_CONCURENT_ID,
			ALERT_BUFFER_DESCRIPTION,ALERT_BUFFER_COMPLETE_STATUS };

	public final String COMMON_SRC_RECORD_ID = "SRC_RECORD_ID";
	public final String COMMON_TICKET_ID = "TICKET_ID";
	public final String COMMON_SRC_CONNECT_ID = "SRC_CONNECT_ID";
	public final String COMMON_STATUS = "STATUS";
	public final String COMMON_CREATE_BY = "CREATE_BY";
	public final String COMMON_CREATION_DATE = "CREATION_DATE";
	public final String COMMON_UPDATED_BY = "UPDATED_BY";
	public final String COMMON_UPDATE_DATE = "UPDATE_DATE";
	public final String COMMON_ERROR_CODE = "ERROR_CODE";
	public final String COMMON_ERROR_DESCRIPTION = "ERROR_DESCRIPTION";

	public final String[] COMMON_ALL_FIELDS = { COMMON_SRC_RECORD_ID,
			COMMON_TICKET_ID, COMMON_SRC_CONNECT_ID, COMMON_STATUS,
			COMMON_CREATE_BY, COMMON_CREATION_DATE, COMMON_UPDATED_BY,
			COMMON_UPDATE_DATE };

	public final String[] COMMON_ALL_FIELDS_UPDATE = { COMMON_STATUS,
			COMMON_ERROR_CODE, COMMON_ERROR_DESCRIPTION };
	// THANHNN
	// SET OF FIELDS ON EVN_ERROR_BUFFER TABLES
	public final String EVN_ERROR_BUFFER_ID = "ERROR_ID";
	public final String EVN_ERROR_BUFFER_CODE = "ERROR_CODE";
	public final String EVN_ERROR_BUFFER_DESCRIPTION = "ERROR_DESCRIPTION";
	public final String EVN_ERROR_BUFFER_MODULE_ID = "MODULE_ID";
	public final String[] EVN_ERROR_BUFFER_ALL_FIELDS = { EVN_ERROR_BUFFER_ID,
			EVN_ERROR_BUFFER_CODE, EVN_ERROR_BUFFER_DESCRIPTION,
			EVN_ERROR_BUFFER_MODULE_ID };
	// SET OF FIELDS ON EVN_MODULE_BUFFER TABLES
	public final String EVN_MODULE_BUFFER_ID = "MODULE_ID";
	public final String EVN_MODULE_BUFFER_CODE = "MODULE_CODE";
	public final String EVN_MODULE_BUFFER_DESCRIPTION = "MODULE_DESCRIPTION";
	public final String EVN_MODULE_BUFFER_ATRIBUTE_1 = "MODULE_ATTRIBUTE_1";
	public final String EVN_MODULE_BUFFER_ATRIBUTE_2 = "MODULE_ATTRIBUTE_2";
	public final String EVN_MODULE_BUFFER_ATRIBUTE_3 = "MODULE_ATTRIBUTE_3";

	public final String[] EVN_MODULE_BUFFER_ALL_FIELDS = {
			EVN_MODULE_BUFFER_ID, EVN_MODULE_BUFFER_CODE,
			EVN_MODULE_BUFFER_DESCRIPTION, EVN_MODULE_BUFFER_ATRIBUTE_1,
			EVN_MODULE_BUFFER_ATRIBUTE_2, EVN_MODULE_BUFFER_ATRIBUTE_3 };

}
